name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

# Allow this job to clone the repo and create a deployment
permissions:
  contents: read
  pull-requests: write
  deployments: write
  
jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          # Genera la salida con una URL base específica para el preview
          build-args: --base=/pr-preview/pr-${{ github.event.number }}
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-preview-${{ github.event.number }}
          path: dist

  deploy-preview:
    needs: build-preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      deployments: write
      statuses: write
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pr-preview-${{ github.event.number }}
          path: dist
      
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: dist
          preview-branch: pr-previews
          umbrella-dir: pr-preview
          action: auto