name: PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      
      # Instalar dependencias y construir (si el PR no está cerrado)
      - name: Install, build, and upload your site
        if: github.event.action != 'closed'
        uses: withastro/action@v3
        with:
          build-args: --base=/pr-preview/pr-${{ github.event.number }}

      # Desplegar el preview al branch gh-pages
      - name: Deploy preview
        if: github.event.action != 'closed'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/
          preview-branch: gh-pages
          umbrella-dir: pr-preview
      
      # Eliminar el preview cuando se cierra el PR
      - name: Remove preview
        if: github.event.action == 'closed'
        uses: rossjrw/pr-preview-action@v1
        with:
          action: remove
          preview-branch: gh-pages
          umbrella-dir: pr-preview